repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: pdm run black
        language: system
        types: [python]
      - id: isort
        name: isort (python)
        entry: pdm run isort
        language: system
        types: [python]
